### ISSUE TITLE
in TwisterOS version, support buttons fail to open web browser

### ISSUE THREAD

**Issue by Itai-Nelken** [libredeb/comice-about#3]
https://user-images.githubusercontent.com/70802936/103472841-e0fe5a00-4d9a-11eb-9287-28ab7cdbc773.mp4

**Comment by libredeb** [comment]
@Itai-Nelken try to run the next command in a terminal:

`xdg-open https://google.com`

You probably don't have a default web browser defined. Try setting one!

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken try to run the next command in a terminal:
> 
> `xdg-open https://google.com`
> 
> You probably don't have a default web browser defined. Try setting one!

@libredeb that opens chromium in google.com, and anyway chromium is my default browser. So that isn't the issue.

**Comment by libredeb** [comment]
> > @Itai-Nelken try to run the next command in a terminal:
> > `xdg-open https://google.com`
> > You probably don't have a default web browser defined. Try setting one!
> 
> @libredeb that opens chromium in google.com, and anyway chromium is my default browser. So that isn't the issue.

Hi @Itai-Nelken ok, let's discard things. I need to check some error/warning message or some log. Can you share me the output of GDB?

In a terminal run the next command:
```bash
gdb com.github.libredeb.comice-about
```
And when GDB loads, execute the command `run`. This will open the app... so, use it and try to open a link from the Support tab and copy me here in a comment the output you get by terminal. Regards!

**Comment by libredeb** [comment]
@Itai-Nelken if you wish, you can try to fix the problem (I'm not sure) with this command: 
```bash
update-alternatives --config x-www-browser
```

**Comment by Itai-Nelken** [comment]
@libredeb when running from gdb, the web browser opens. But when running from the menu shortcut, I get the same error.

**Comment by Itai-Nelken** [comment]
@libredeb I found what was wrong: when I compiled and installed the first time the app didn't run without `sudo` for some reason, so I added `sudo` to the menu shortcut. and even though I uninstalled before updating to TwisterOS 1.9.6 (that installs it) the `sudo` stayed there. so I removed it and know everything works great.

Thanks for making this great and fun app!

**Comment by libredeb** [comment]
@Itai-Nelken oooh great! thanks for the feedback... Enjoy and Regards!
